name: First Maven Pipeline

# eventos que gatillan el workflow
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# trabajos
jobs:
  build_1:
    runs-on: ubuntu-latest
    container: maven:3.8.5-openjdk-17
    steps:
    - uses: actions/checkout@v6

    - name: Build with maven 
      run: mvn clean package -DskipTests
    
  test:
    runs-on: windows-latest
    needs: build_1
    steps:
    - uses: actions/checkout@v6



